

def return_site_data():
    return [
        {"name": "www.baidu.com", "id": 1},
        {"name": "www.douban.com","id":2},
        {"name": "www.zhihu.com","id":3},
        {"name": "www.github.com","id":4},
        {"name": "www.lawone.com","id":5},
        {"name": "www.test1.com","id":6},
        {"name": "www.test7.com","id":7},
        {"name": "www.test8.com","id":8},
        {"name": "www.test9.com","id":9},
        {"name": "www.test10.com","id":10},
        {"name": "www.test11.com","id":11},
        {"name": "www.test12.com","id":12},
        {"name": "www.law1.com","id":13},
        {"name": "www.law1.com","id":14},
        {"name": "www.law1.com","id":15},
        {"name": "www.law1.com","id":16},
        {"name": "www.law1.com","id":17},
        {"name": "www.law1.com","id":18},
        {"name": "www.law1.com","id":19},
        {"name": "www.law1.com","id":20},
        {"name": "www.law1.com","id":21},
        {"name": "www.law1.com","id":22},
        {"name": "www.law1.com","id":23},
        {"name": "www.law1.com","id":24},
        {"name": "www.law1.com","id":25},
        {"name": "www.law1.com","id":26},
        {"name": "www.law1.com","id":27},
        {"name": "www.law1.com","id":28},
        {"name": "www.law1.com","id":29},
        {"name": "www.law1.com","id":30},
        {"name": "www.law1.com","id":31},
        {"name": "www.law1.com","id":32},
        {"name": "www.law1.com","id":33}
    ]